---
- name: Playbook to Update Debian security packages, upgrade packages, download Docker, and build docker image for Wordpress
  hosts: hostserver
  become: true
  gather_facts: False

  tasks:
    - name: Update Ubuntu repos and cache via apt
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install unattended-upgrades on Ubuntu server
      apt:
        name:
          [
            unattended-upgrades
          ]
        update_cache: yes

    - name: Install prerequisites for Docker repository
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "gnupg2",
            "software-properties-common",
            "python3-docker"
          ]
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

    - name: Install Docker CE
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        update_cache: yes

    # - name: Install Docker
    #   ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

    - name: Install prerequisites for docker-compose
      apt:
        name: ["python3-pip", "python3-setuptools", "virtualenv"]
        update_cache: yes

    # - name: Install docker-compose
    #   pip:
    #     name: docker-compose
    #     update_cache: yes

    - name: Install docker-compose from official github repo
      remote_user: ansible_ubuntu_demo
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
        
    - name: Build MariaDB server
      docker_container:
        image: mariadb
        name: mariadb
        volumes:
          - "/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: samplerootpass
          MYSQL_PASSWORD: samplepass
          MYSQL_DATABASE: db
          MYSQL_USER: sampleuser

    - name: Build WordPress
      docker_container:
        image: wordpress
        name: wordpress
        restart_policy: always
        ports:
          - "8080:80"
        links:
          - "mariadb:/var/lib/mysql"
        volumes:
          - "/var/www/html"
        env:
          MYSQL_PASSWORD: samplepass
          MYSQL_DATABASE: db
          MYSQL_USER: sampleuser
          MYSQL_HOST: mariadb
