---
- name: Playbook to Update Debian security packages, upgrade packages, download Docker, and build docker image for Wordpress
  hosts: all
  become: yes
  gather_facts: False

  tasks:
    - name: Update Ubuntu repos and cache via apt
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes
    - name: Install prerequisites for Docker repository
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "gnupg2",
            "software-properties-common",
          ]
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

    - name: Install Docker CE
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        update_cache: yes

    - name: Install prerequisites for docker-compose
      apt:
        name: ["python3-pip", "python3-setuptools", "virtualenv"]

    - name: Install docker-compose
      pip:
        name: docker-compose
